name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t godemo:latest .
    - name: list docker image
      run: docker image ls
    - name: docker login
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
          registry_url: 'ccr.ccs.tencentyun.com'
          namespaces: 'silan'
          repository_name: 'c_frontend'
          user_name: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_version: 'latest'
          docker_file: '.'
